# Generated by Django 4.0.6 on 2022-07-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Organizer_App', '0004_user_course_user_name_user_section_user_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='section',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=1, max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
