# Generated by Django 4.0.6 on 2022-07-20 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Organizer_App', '0005_remove_user_name_remove_user_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student_Organizer_App.section'),
        ),
    ]
