# Generated by Django 4.0.6 on 2022-07-20 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Organizer_App', '0006_user_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='classmates',
        ),
        migrations.AddField(
            model_name='topic',
            name='classmates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classmates', to=settings.AUTH_USER_MODEL),
        ),
    ]
