# Generated by Django 4.0.6 on 2022-07-21 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Organizer_App', '0008_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
